# Generated by Django 5.1.7 on 2025-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/avatar/coder.jpg', upload_to='media/avatar/'),
        ),
    ]
