# Generated by Django 5.1.7 on 2025-04-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Toifa nomi')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LessonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, verbose_name='Kursning nomi')),
                ('lesson_banner', models.ImageField(upload_to='media/banner/', verbose_name='Banner rasm')),
                ('lesson_price', models.CharField(default='Bepul', max_length=7, verbose_name='Kurs narxi')),
                ('lesson_author_name', models.CharField(default='admin', max_length=50, verbose_name='Dars muallifi')),
                ('lesson_description', models.CharField(default='', max_length=500, verbose_name="Dars haqida umumiy ma'lumot")),
                ('lesson_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lessons.category', verbose_name='Toifasi')),
            ],
            options={
                'verbose_name': 'LessonName',
                'verbose_name_plural': 'LessonNames',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.FileField(upload_to='media/videos/', verbose_name='Darslar')),
                ('lessons_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lessons.lessonname')),
            ],
            options={
                'verbose_name': 'Lessons',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Izoh')),
                ('datetime_comment', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lessons.lessons')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_nums', models.CharField(max_length=16, verbose_name='Karta raqami')),
                ('card_expiry', models.CharField(max_length=5, verbose_name='Kartani amal qilish muddati')),
                ('paymend_price', models.CharField(max_length=7, verbose_name="To'lov qilingan summa")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_lessons.lessonname')),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Baho')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stars_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lessons.lessons')),
            ],
            options={
                'verbose_name': 'Stars',
                'verbose_name_plural': 'Stars',
                'constraints': [models.UniqueConstraint(fields=('from_user', 'stars_lesson'), name='unique_user_lesson_rating')],
            },
        ),
    ]
