# Generated by Django 5.1.7 on 2025-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonname',
            name='lesson_author_name',
            field=models.CharField(default='admin', max_length=50, verbose_name='Dars muallifi'),
        ),
        migrations.AddField(
            model_name='lessonname',
            name='lesson_description',
            field=models.CharField(default='', max_length=500, verbose_name="Dars haqida umumiy ma'lumot"),
        ),
    ]
